### ISSUE TITLE
[Enhancement] Permits to unload a cartridge

### ISSUE THREAD

**Issue by wwark** [tdlabac/MSX1_MiSTer#11]
To unload the cartridge, the only possibility is to restart the core (if we want to launch a dsk or a cas game) or load a new cartridge.
It will be great to add a reset with detach cartridge like the C64 core.

Thanks !

**Comment by wwark** [comment]
Thank you for the quick update :)

**Comment by GuerreroNinja** [comment]
Wow that was fast! Thank you!
