### ISSUE TITLE
Audio is too high-pitched in every game

### ISSUE THREAD

**Issue by vanfanel** [tdlabac/MSX1_MiSTer#13]
Hi,

I have noticed that with today's version (20221023) music in every game sounds VERY high-pitched.
Any game will do the same.

I guess something went wrong on the JT49 update? Only guessing here...

**Comment by tdlabac** [comment]
Fixed

**Comment by GuerreroNinja** [comment]
Superb, thank you! Will you synthesize a release with the fixed sound problem?
