### ISSUE TITLE
SCC sound is not accurate

### ISSUE THREAD

**Issue by GuerreroNinja** [tdlabac/MSX1_MiSTer#14]
SCC sound does not match original SCC. You can test it by loading Salamander or Nemesis 2 in OCM core (MSX official core) and then loading them in the MSX1 core. The differences are quite noticeable.

**Comment by tdlabac** [comment]
Please try this edition. I found two bugs causing an error in SCC waveform playback. [https://github.com/tdlabac/MSX1_MiSTer/blob/Slots/releases/MSX1_20221127_slots.rbf](url)

**Comment by GuerreroNinja** [comment]
Thank you! Checking it right now...

**Comment by GuerreroNinja** [comment]
Ok, tested some titles and now they sound right, OK to my ears, but I have to compare to real hardware (will do tonight if I can get some spare time). BIG improvement, thank you!!

EDIT: Tested Salamander and it sounds PERFECT to me.

**Comment by tdlabac** [comment]
Fix in release 20221127
