### ISSUE TITLE
R-type ROM not working

### ISSUE THREAD

**Issue by nonochus** [tdlabac/MSX1_MiSTer#18]
R-type is not working, it uses a "almost" ascii 16k mapper.

R-Type (384kB) uses same mapper but the segment 0Fh remains fixed on page 4000h~7FFFh. In addition, the segment 0Fh is same as 17h (the last segment).

Here more info in sction ascii16k:

https://www.msx.org/wiki/MegaROM_Mappers

**Comment by GuerreroNinja** [comment]
That one is indeed a rare one, I will try to test the modifications proposed in the MSX Resource Center thread to make it compatible with the MegaFlashROM (maybe that way it can load on the MSX1 core).

**Comment by nonochus** [comment]
Yes, have is own mapper,  a special mapper, almost a ascII16k  with some diferences, more info here too:

http://bifi.msxnet.org/msxnet/tech/megaroms#rtype

I see the MSX Resource Center thread maybe better make modificantions mencioned por ascii16k mapper?

P.D:  If your patch the rom, can you send me the patched rom for testing, via telegram for example?

**Comment by GuerreroNinja** [comment]
Yes, I will patch the ROM and check it along the week. If it works I will upload it somewhere for you to test.

**Comment by nonochus** [comment]
[R-Type - IREM (1988) [Japan] [AscII8K].zip](https://github.com/tdlabac/MSX1_MiSTer/files/9995303/R-Type.-.IREM.1988.Japan.AscII8K.zip)

While it is solved, for those who want to play it, I leave here a modified R-type ROM to play in ASCII 8K mapper, it is tested and works.

Thanks to Jc Galvans from the MIster PFGA group in Spanish for the rom.

I suppose that to solve that the original one works, I will have to add one more "rtype" mapper, which has been the ascii16k mapper with the modifications that were made to it in its day for this rom.

Enjoy!

**Comment by GuerreroNinja** [comment]
Thank you, really not worth the hassle to add a mapper just for one game? The patched ROM will also be useful for MSX MFR users (and others that use LOADROM).

**Comment by nonochus** [comment]
Yes and no, "yes" because it has the original rom working and it is the closest thing to a real msx1, it would be necessary to add a new maper and modify the ascII16k maper and "no" because it is already working and it is just a game ...... maybe a very low priority for it to be solved? I'm not in a hurry or if you want I'll close the issue. Personally, I think that the mapper should be added and have everything as close to the real hard as possible.

**Comment by GuerreroNinja** [comment]
Well, only you and @tdlabac can close the issue :D, your choice.

**Comment by nonochus** [comment]
@tdlabac I leave it to your choice, it is already working with the modified rom, if you close it for me it's fine and if you prefer to leave it open to add the RTYPE maper in the future and make it as close to a real msx hardware, without any hurry with low priority, for me it's fine too.Your decision is welcome.

**Comment by tdlabac** [comment]
I've already made the necessary adjustments this morning, but I'm just now getting to the finishing touches.

**Comment by tdlabac** [comment]
Added R-type mapper to the core. It is not detected automatically. It must be selected manually in the menu.

**Comment by GuerreroNinja** [comment]
Thank you!

**Comment by nonochus** [comment]
Very Thanks!!!!

**Comment by wwark** [comment]
Thanks ! Testing it is working great :+1:
