### ISSUE TITLE
[ENHANCEMENT] HDD interface

### ISSUE THREAD

**Issue by Petracus** [tdlabac/MSX1_MiSTer#19]
BeerIde is a very simple hd interface specially designed for msx1. No memory upgrade or msxdos 2 required.

It would be very interesting to be able to select between a floppy drive and this interface, which allows loading images of up to 128mb (4 partitions of 32mb).

Here is the schematic and its firmware:

https://hansotten.file-hunter.com/do-it-yourself/beer-ide/

With this interface you can load images like this:

https://mega.nz/file/lHpjTIqC#Hr5dRzUfV8JLkH8zcaZ1uQ_0_uvJ3LVtSDSQEpNP8Mc

Cheers,

**Comment by tdlabac** [comment]
The interface is simple, but emulating an SD card or hard drive on MiSTter is no longer simple.
This is because all the logic is in the firmware.
I have no ambition to even try this.
