### ISSUE TITLE
STOP key in the keyboard?

### ISSUE THREAD

**Issue by juanfx** [tdlabac/MSX1_MiSTer#20]
Greetings, I have been enjoying this core for some time now, following its progress and getting happier every day. What I can't find on the keyboard is the STOP key, essential in the use of the basic interpreter.

A quick example in basic:

10 goto 10
run
(impossible to stop without the combination CTRL+STOP).

Where is this key located?

Also, I don't know what the right SHIFT key is used for, it should do the same as the left SHIFT key.

Translated with www.DeepL.com/Translator (free version) < ---- Sorry

**Comment by tdlabac** [comment]
Both SHIFT key is now work.
STOP key is mapped to key Print Screen
New version is published 20221111
