### ISSUE TITLE
MSX Diag doesn't show the correct Freq in NTSC video mode

### ISSUE THREAD

**Issue by wwark** [tdlabac/MSX1_MiSTer#21]
Hi,
In this case, I use the bios MSX JB HB-201 and set video mode to NTSC.

In the MSX Diag, the keyboard is set correctly to JP but the FREQ value is 50Hz.
![20221112_001445-msxdiag](https://user-images.githubusercontent.com/469461/201443277-e1ea155d-791c-4068-8885-085ecb49cbf5.png)

Is it normal ?
Thanks for your time :+1:  very glad of your work !!!

**Comment by wwark** [comment]
Test RAM 1.0 shows 60Hz
![20221112_002257-testram](https://user-images.githubusercontent.com/469461/201443638-b3e0ff4d-c9ec-4dcd-9818-98559889ba7c.png)

**Comment by GuerreroNinja** [comment]
Maybe the MSX Diag with the HB-201 BIOS show the VDP version instead of the freq mode?

**Comment by wwark** [comment]
Trying on Mame with HB 201.
The VDP is different.
![image](https://user-images.githubusercontent.com/469461/201465003-f823fe41-fd80-408e-a01c-af960ff6cec4.png)

But I read the VDP used on the core is from Coleco and it was NTSC.

**Comment by GuerreroNinja** [comment]
The TMS9918A/28A is NTSC, while the TMS9929A is PAL. I suspect MSX Diag just read the VDP model and that's all. The core implements the TMS9929A, so the expected behaviour in MSX Diag is OK, I see no bug here?

https://www.msx.org/wiki/Texas_Instruments_TMS9918

**Comment by wwark** [comment]
ok so not real frequence of the core.
I see.
I will close this ticket. Thank your for your time :+1:

**Comment by wwark** [comment]
![20221115_210313-msxdiag](https://user-images.githubusercontent.com/469461/202014722-c65d0a49-4d00-49cb-b234-e5adfdf87e7f.png)
Now we can use boot.rom (hb 201 MSX1)
The MSX DIAG shows the VDP of HB201 and the good freq for information.

**Comment by GuerreroNinja** [comment]
Yes, as I supposed MSX Diag just read the BIOS and set the VDP accordingly. So, the right approach here in order to enjoy NTSC is changing the OSD option AND the BIOS, just in case any game checks that (dunno though if there is one...).
