### ISSUE TITLE
Please reset the mapper back to [auto] after loading a new ROM

### ISSUE THREAD

**Issue by Vampier** [tdlabac/MSX1_MiSTer#23]
Would it be possible to reset the mapper to auto when a new ROM is loaded? 

Scenario: I was testing a few ROMs for known 'problematic' MSX1 games - After running Vaxol - Heavy Armed Storm Vehicle I booted Nemesis 3 (auto/Konami SCC) and the mapper was set to ASCII16 (Vaxol Mapper - auto doesn't work there)

**Comment by tdlabac** [comment]
What is selected in the MiSTer menu cannot be changed from core to something else.
