### ISSUE TITLE
Support SRAM saves for games required it.

### ISSUE THREAD

**Issue by wwark** [tdlabac/MSX1_MiSTer#24]
Hi,

You have this game "Hydlide II - Shine of Darkness (1986)(T&E Soft)(Japan)(MSX1)(ASCII8).rom" that you need to create a character before to start the game.
The creation is OK but after create the character, the game start said "Nothing" because I think It tried to read the SRAM.
So maybe this game is easy to check the SRAM save implementation.

![image](https://user-images.githubusercontent.com/469461/201675845-b2e8041d-05cd-489b-ace2-7c8e4558e090.png)

Thanks for your time on this great core !!

**Comment by Vampier** [comment]
Those are very specific mappers that are used for those games - I'm not sure if simply adding an SRAM functionality would do the trick. Also the filename mentions ASCII8 which is incorrect ;) 

https://romdb.vampier.net/edit.php?id=462

**Comment by wwark** [comment]
I see so new slots to implement for this case.
Do you know if the rom contains this information or we will need to choose the slot(mapper) for this game ?
Thanks !

**Comment by GuerreroNinja** [comment]
> I see so new slots to implement for this case. Do you know if the rom contains this information or we will need to choose the slot(mapper) for this game ? Thanks !

There is a database that describe the mapper used for every MSX game out there based on rom hash. Perhaps it can be used here, I don't know if the Mister framework allows that or can be doable?

**Comment by wwark** [comment]
List of SRAM mappers for MSX1:
- KoeiSRAM32 (Genghis Khan, Nobunaga no Yabou - Zenkokuhan)
- ASCII16SRAM2 (Hydlide 2)
- ASCII8SRAM8 (Xanadu, Deep Dungeon 2(alt))
- ASCII8SRAM2 (Deep Dungeon 1, Deep Dungeon 2)

Maybe some games are missing on list let me know

**Comment by Vampier** [comment]
> > I see so new slots to implement for this case. Do you know if the rom contains this information or we will need to choose the slot(mapper) for this game ? Thanks !
> 
> There is a database that describe the mapper used for every MSX game out there based on rom hash. Perhaps it can be used here, I don't know if the Mister framework allows that or can be doable?

I am the owner of romdb.vampier.net I reached out on Twitter about this as well - but I am not sure if the framework allows this indeed.

**Comment by tdlabac** [comment]
> There is a database that describe the mapper used for every MSX game out there based on rom hash. Perhaps it can be used here, I don't know if the Mister framework allows that or can be doable?

This would mean adding support to the Mister OS and framework

**Comment by wwark** [comment]
With the last update with support of some mappers using SRAM I can start the game Hidlyle II after the character creation.
Thank you :+1: 

![20221130_194820-Hydlide II - Shine of Darkness (1986)(T E Soft)(Japan)(MSX1)(ASCII8)](https://user-images.githubusercontent.com/469461/204883362-2dad5597-6838-4632-bb71-908fecfffc26.png)
