### ISSUE TITLE
There is additional bios for Korean input system.

### ISSUE THREAD

**Issue by tdlabac** [tdlabac/MSX1_MiSTer#26]
First of all, many thanks for this great MSX1 core ever.

Now I'd like to talk about Korean MSX1.
There is additional bios for Korean input system.
![Screenshot_20221125_210740](https://user-images.githubusercontent.com/21172516/203982942-2f513e70-4721-4a67-b70b-982efc2be8c1.jpg)

If we increase the rom size from 32kB to 64kB, the system can access the hangul ROM in 0x8000-0xBFFF.

I modified the code like below.
![image0](https://user-images.githubusercontent.com/21172516/203983913-4585ed21-06ef-4ca8-ae87-8ba2d0c907f5.png)
![image](https://user-images.githubusercontent.com/21172516/203983938-7478206c-7f4c-4785-b88d-51c383b7fed1.png)

Then I could successfully launch the Korean MSX.
![20221122_013847](https://user-images.githubusercontent.com/21172516/203984102-47048437-0026-4895-9277-9c90d51587ab.jpg)

Is there any chance to support loading Korean Bios rom?

_Originally posted by @juntaesu in https://github.com/tdlabac/MSX1_MiSTer/issues/15#issuecomment-1327405238_

**Comment by tdlabac** [comment]
Added in Release 20221127

EDIT: firmware/hangul ROM loaded automatically if /media/fat/games/MSX1/boot1.rom exists

**Comment by wwark** [comment]
Great I can load Sony contents also for HB201 MSX
![20221127_185224-screen](https://user-images.githubusercontent.com/469461/204151688-f4dc8f4e-29c8-49b6-aee7-f4d7159a71f0.png)

Thank you for your hard work

**Comment by juntaesu** [comment]
> Added in Release 20221127
> 
> EDIT: firmware/hangul ROM loaded automatically if /media/fat/games/MSX1/boot1.rom exists

Thank you so much for this!!
