### ISSUE TITLE
2 roms file hang in MSX system version 1.0 screen 

### ISSUE THREAD

**Issue by wwark** [tdlabac/MSX1_MiSTer#3]
Thank you for this core !

During my tests, I found two games hang at this screen.
![20220228_094307-Crazy Train (1983)(Konami)(Japan)(MSX1)(Linear)](https://user-images.githubusercontent.com/469461/155952038-96dc9330-baa3-4f84-9014-ea205d593792.png)

The games are:
Sha1sum - name
- 8aca0ee5845b0b39af624e8a998bb04f02d0fda4  Crazy Train (1983)(Konami)(Japan)(MSX1)(Linear).rom
- 122f659250a0ae10ce0be0dde626dd3e384affa7  King's Knight (1986)(Square)(Japan)(MSX1)(ASCII16).rom

Thanks again

**Comment by tdlabac** [comment]
Hi, 

both games don't work in the Mame emulator either. 
In King's Knight, the mapper type is not detected correctly. It needs to be manually defined. It will be supported by other core.
Does Crazy Train work on another computer ? I don't see how it boots into RAM.

**Comment by wwark** [comment]
Hi,

Thank you for the check !
Normally I used on Mame HB-201 (Japan) for MSX1 and both games work.

So I tried with VG8020-20 (MSX1) and I managed to launch games on Mame. 
I get roms from mame set to test on the core but still hang.
Is it the correct version of MSX1 I need to use for the test ?
You can see screenshot below
For Crazy Train
![Screenshot from 2022-03-05 18-48-15](https://user-images.githubusercontent.com/469461/156894697-a45a6521-732f-44a7-9a33-3ee6c77c445b.png)
![Screenshot from 2022-03-05 18-48-25](https://user-images.githubusercontent.com/469461/156894700-92dfa68f-434a-4ce1-a932-7a0617ad35f2.png)
![Screenshot from 2022-03-05 18-48-34](https://user-images.githubusercontent.com/469461/156894703-4e07d288-3fd9-4f63-a50f-8ef0abddf2ca.png)
![Screenshot from 2022-03-05 18-48-38](https://user-images.githubusercontent.com/469461/156894704-c201dace-b837-401a-9983-cba9ed097d8b.png)
![Screenshot from 2022-03-05 18-48-44](https://user-images.githubusercontent.com/469461/156894705-ad2befce-887b-4660-af23-c1ba6c6f23e5.png)
For King's Knight:
![Screenshot from 2022-03-05 18-49-02](https://user-images.githubusercontent.com/469461/156894732-a0d9790b-5a23-458d-a8d2-842987b402e5.png)
![Screenshot from 2022-03-05 18-49-14](https://user-images.githubusercontent.com/469461/156894736-eaa01478-51f5-4fd1-8790-72882dfbb007.png)
![Screenshot from 2022-03-05 18-49-21](https://user-images.githubusercontent.com/469461/156894739-eebd8158-375f-4920-934f-a645d7dbd03b.png)
![Screenshot from 2022-03-05 18-49-26](https://user-images.githubusercontent.com/469461/156894740-7c7ee981-f93d-40e3-ae73-e18a2af6e101.png)
![Screenshot from 2022-03-05 18-49-42](https://user-images.githubusercontent.com/469461/156894741-305b11a9-e554-4b42-9102-b1a9e096f68b.png)

Thanks.

**Comment by tdlabac** [comment]
Hi, 

I've gone through the Mame jake works with ROMs for non-functional games. For these ROMs autodetection does not work and you need to use the HW cartrige definition for the specific ROM. For Crazy train, the code needs to be mirrored on multiple ROM pages. I have added a mapper selection option to the menu. This option takes precedence over the automatically detected mapper. For Crazy train you need to select linear 64k. 

New version published.

**Comment by wwark** [comment]
Thanks a lot !
It is working great for both games !
The linear 64k may help also two others games I think because they used the same mirroring 
- Sparkie (Jpn)
- Juno First (Jpn)
