### ISSUE TITLE
Sound FX interacting with joystick

### ISSUE THREAD

**Issue by aloyisus** [tdlabac/MSX1_MiSTer#5]
Thanks so much for the previous joystick fix in MSX1_20220305.rbf. I have one more similar issue to raise and then I promise I'll go bother someone else for a while ;)

The game is:
Colony (1987)(Bulldog)

and this time there are seemingly no problems until sound effects are played, which then seems to interfere with the joystick input rendering the game unplayable.

Again I have pulled out the relevant code into a test example:
[joycol.zip](https://github.com/tdlabac/MSX1_MiSTer/files/8193112/joycol.zip)

The joystick code in this game is almost identical to one of your test examples (interrupts are cancelled, and I think B0-B3 are set to high) so hopefully it works better.

**Comment by tdlabac** [comment]
Fixed. commit #20ff16d5dacd9cfc54d2c39106d32725259d0e94

**Comment by aloyisus** [comment]
Thanks for fixing this, works great now
