### ISSUE TITLE
Input issue with the game BITLOGIC Free Mind

### ISSUE THREAD

**Issue by wwark** [tdlabac/MSX1_MiSTer#7]
Hi,

This game seems to have an input issue. Without any action he shoots and I can't move him with keyboard or gamepad
https://jamque.itch.io/bitlogic-msx-a-cyberpunk-arcade-adventure

Thanks !

**Comment by tdlabac** [comment]
Fixed. commit #20ff16d5dacd9cfc54d2c39106d32725259d0e94

**Comment by wwark** [comment]
Thanks a lot. It is working great now :+1:
