### ISSUE TITLE
[Enhancement] Adding a disk controller and ROM

### ISSUE THREAD

**Issue by GuerreroNinja** [tdlabac/MSX1_MiSTer#8]
This is an enhancement petition, not a bug. 

In the VG 8020 (or any MSX 1) we have disk controllers as cartridges to add a disk drive. Would be possible to add a controller and the MSX disk ROM to the core?

Thank you!

**Comment by tdlabac** [comment]
Can I ask for a link to the documentation and SW of this extension? I have never owned an MSX computer. I would evaluate the possibilities.

**Comment by GuerreroNinja** [comment]
MSX 1 Disk support is done through MSX-DOS 1, (https://www.msx.org/wiki/Disk_ROM). As VG 8020 does not integrate a disk controller, a external cartridge with the controller and BIOS should be attached to one of the cartridge ports. It can be a Philips VY0010/11 (https://hansotten.file-hunter.com/uploads/files/philipsvy0010.pdf) or for example a TDC-600 controller (https://www.msx.org/wiki/Talent_TDC-600).

The driver for the TDC-600 is here: https://sourceforge.net/p/msxsyssrc/git/ci/master/tree/diskdrvs/tdc600/driver.mac

The TDC-600 cartridge include the ROM with driver and Disk Basic instructions, here is the ROM: http://msx2.org/NewPack/Hardware/Roms/Interfaces%20por%20Mem%C3%B3ria/Talent%20TDC%20600/TDC600.rom

I am just adding a quick response now, but I asked some retro users and are willing to help with this matter, feel free to tell me what you need and we will begin working on it. I will add more documentation and sources this weekend.

Thank you!!!

**Comment by tdlabac** [comment]
I published a branch of [FloppyDrive](https://github.com/tdlabac/MSX1_MiSTer/tree/FloppyDrive). Try the created [rbf](https://github.com/tdlabac/MSX1_MiSTer/blob/FloppyDrive/releases/MSX1_20221016_fdd.rbf)

**Comment by GuerreroNinja** [comment]
Wow!!! Thank you!!! You are the best really!! Tried some loading some disks and works perfectly, I will test it along the day and report any bug I may find.

**Comment by GuerreroNinja** [comment]
Tested lots of disk images, no bugs related to disk implementation encountered so far. Works great!
