### ISSUE TITLE
[Bug] Music in "Invasion of the Zombie Monsters" is missing a percussion channel

### ISSUE THREAD

**Issue by vanfanel** [tdlabac/MSX1_MiSTer#9]
Hi there,

With the recent developments, this core caught my attention once again. Great work!

However, I found that "Invasion of the Zombie Monsters" fantastic intro music is missing a percussion channel .
This is how the intro is supposed to sound:

https://www.youtube.com/watch?v=6gUEqk3ie_4
(Music is faster because it's being emulated at 60Hz, but this is a PAL game).

As you will see, there's a missing percussion audio channel on this fantastic MSX1 core, which can be clearly heard in the video.

The game is freely available, so here it is to save you some time:
[Invasion_of_the_Zombie_Monsters_MSX.zip](https://github.com/tdlabac/MSX1_MiSTer/files/9795494/Invasion_of_the_Zombie_Monsters_MSX.zip)

Could you take a look, please? Seems like a major inaccuracy in the audio implementation.

**Comment by tdlabac** [comment]
Fixed in today's version

**Comment by vanfanel** [comment]
Wow! Thanks a lot, @tdlabac 

This is my dream MSX core now! :dancers:
